name: Deploy Terraform to Azure

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

permissions:
  id-token: write  # Allow the workflow to request an ID token
  contents: read   # Allow access to the repository contents

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the GitHub repository (if this is where your workflow is defined)
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.10.5'  # specify your desired version of Terraform

      # Set up Azure credentials using GitHub Secrets
      - name: Set up Azure credentials
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: 'service-principal'  # Use service principal with client secret


      # Clone the Azure Repos repository using the PAT stored in GitHub Secrets
      - name: Clone Azure Repos Terraform repository
        run: |
          git clone https://$(System.AccessToken):${{ secrets.AZURE_REPO_PAT }}@dev.azure.com/williamcastelino99/TestProject/_git/az-root
          cd az-root

      # Install dependencies for Terraform (e.g., initialize Terraform)
      - name: Install Terraform dependencies
        run: terraform init

      # Run Terraform plan
      - name: Terraform Plan
        run: terraform plan

      # Apply the Terraform plan (be careful with auto-approval)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

