name: Terraform Azure Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the az-root repository (the repository containing the Terraform code)
      - name: Checkout az-root repository
        uses: actions/checkout@v2

      # Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.4.0'

      # Set up Azure credentials using Service Principal (for Azure resource deployment)
      - name: Set up Azure credentials for Service Principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Set up Git credentials for Azure Repos (using PAT to authenticate with Azure Repos)
      - name: Set up Git credentials for Azure Repos
        run: |
          git config --global credential.helper 'store --file=.git-credentials'
          echo "https://$(echo ${{ secrets.AZURE_DEVOPS_PAT }}):@dev.azure.com" > ~/.git-credentials

      # Initialize Terraform (this will download the az-network module from Azure Repos)
      - name: Terraform Init
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
